// flow-typed signature: 7bf6a46c36860e3f97c5fbf927068657
// flow-typed version: <<STUB>>/@watson/eslint-config-watson_v^0.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@watson/eslint-config-watson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@watson/eslint-config-watson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@watson/eslint-config-watson/plugins/babel' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/plugins/flowtype' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/plugins/import' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/plugins/react-a11y' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/plugins/react' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/rules/base' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/rules/best-practices' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/rules/es6' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/rules/node' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/rules/strict' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/rules/style' {
  declare module.exports: any;
}

declare module '@watson/eslint-config-watson/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module '@watson/eslint-config-watson/index' {
  declare module.exports: $Exports<'@watson/eslint-config-watson'>;
}
declare module '@watson/eslint-config-watson/index.js' {
  declare module.exports: $Exports<'@watson/eslint-config-watson'>;
}
declare module '@watson/eslint-config-watson/plugins/babel.js' {
  declare module.exports: $Exports<
    '@watson/eslint-config-watson/plugins/babel'
  >;
}
declare module '@watson/eslint-config-watson/plugins/flowtype.js' {
  declare module.exports: $Exports<
    '@watson/eslint-config-watson/plugins/flowtype'
  >;
}
declare module '@watson/eslint-config-watson/plugins/import.js' {
  declare module.exports: $Exports<
    '@watson/eslint-config-watson/plugins/import'
  >;
}
declare module '@watson/eslint-config-watson/plugins/react-a11y.js' {
  declare module.exports: $Exports<
    '@watson/eslint-config-watson/plugins/react-a11y'
  >;
}
declare module '@watson/eslint-config-watson/plugins/react.js' {
  declare module.exports: $Exports<
    '@watson/eslint-config-watson/plugins/react'
  >;
}
declare module '@watson/eslint-config-watson/rules/base.js' {
  declare module.exports: $Exports<'@watson/eslint-config-watson/rules/base'>;
}
declare module '@watson/eslint-config-watson/rules/best-practices.js' {
  declare module.exports: $Exports<
    '@watson/eslint-config-watson/rules/best-practices'
  >;
}
declare module '@watson/eslint-config-watson/rules/es6.js' {
  declare module.exports: $Exports<'@watson/eslint-config-watson/rules/es6'>;
}
declare module '@watson/eslint-config-watson/rules/node.js' {
  declare module.exports: $Exports<'@watson/eslint-config-watson/rules/node'>;
}
declare module '@watson/eslint-config-watson/rules/strict.js' {
  declare module.exports: $Exports<'@watson/eslint-config-watson/rules/strict'>;
}
declare module '@watson/eslint-config-watson/rules/style.js' {
  declare module.exports: $Exports<'@watson/eslint-config-watson/rules/style'>;
}
declare module '@watson/eslint-config-watson/rules/variables.js' {
  declare module.exports: $Exports<
    '@watson/eslint-config-watson/rules/variables'
  >;
}
